### ISSUE TITLE
Potential Spam Abuse with URL Fragment Identifier

### ISSUE THREAD

**Issue by SadaleNet** [ccbikai/loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ong#1]
Your project looks interesting. In fact, I've made something similar years ago. Unfortunately, my site ended up getting abused by spammers and I don't want that to happen again in your project.

I've made a post on HN and I'm crossposting it here just in case you missed it. Please consider disabling usage of URL fragment identifier on your site somehow. You can find the details here: https://news.ycombinator.com/item?id=40544240

**Comment by miantiao-me** [comment]
Thank you very much for your reminder and sharing. I have just updated the program to remove the server-side redirection.

And added a reminder on the webpage.

I hope it can live longer

**Comment by chenxuuu** [comment]
I use a secret solution for llili.li to prevent this happend, it will automatic jump to trusted URL, but show a notice page for other URL.

I can't make this public otherwise someone may break this rule.

**Comment by miantiao-me** [comment]
> I use a secret solution for llili.li to prevent this happend, it will automatic jump to trusted URL, but show a notice page for other URL.
> 
> I can't make this public otherwise someone may break this rule.

Can you share the plan with me? My email is: chi@miantiao.me
